// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2LfODEYIyBiZcv8Gb5LXEkYJR_lWle9U',
    appId: '1:305479187272:web:6f708dfd7cbcdc11da517d',
    messagingSenderId: '305479187272',
    projectId: 'planetinfo-3c0f1',
    authDomain: 'planetinfo-3c0f1.firebaseapp.com',
    storageBucket: 'planetinfo-3c0f1.firebasestorage.app',
    measurementId: 'G-X1XR1729L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOZfrkv1NrpcGXjDf4nQXMGRJhks7b6SY',
    appId: '1:305479187272:android:31e5d07542eedea4da517d',
    messagingSenderId: '305479187272',
    projectId: 'planetinfo-3c0f1',
    storageBucket: 'planetinfo-3c0f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW1ov3_-ZRUQTWhy6Rli2FYEYbL3AqrKk',
    appId: '1:305479187272:ios:b94b182fb718a9f4da517d',
    messagingSenderId: '305479187272',
    projectId: 'planetinfo-3c0f1',
    storageBucket: 'planetinfo-3c0f1.firebasestorage.app',
    iosBundleId: 'com.example.planetInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW1ov3_-ZRUQTWhy6Rli2FYEYbL3AqrKk',
    appId: '1:305479187272:ios:b94b182fb718a9f4da517d',
    messagingSenderId: '305479187272',
    projectId: 'planetinfo-3c0f1',
    storageBucket: 'planetinfo-3c0f1.firebasestorage.app',
    iosBundleId: 'com.example.planetInfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2LfODEYIyBiZcv8Gb5LXEkYJR_lWle9U',
    appId: '1:305479187272:web:1bddb944889ff499da517d',
    messagingSenderId: '305479187272',
    projectId: 'planetinfo-3c0f1',
    authDomain: 'planetinfo-3c0f1.firebaseapp.com',
    storageBucket: 'planetinfo-3c0f1.firebasestorage.app',
    measurementId: 'G-KS9V1RB6W7',
  );
}
